### ISSUE TITLE
Object not found in enable_webapp recipe

### ISSUE THREAD

**Issue by bilgeadam61** [atul86244/spring-petclinic#5]
Hi Atul.

When I tried to botstrap a node with petclinic cookbok. I got a Net::HTTPServerException 404 "Object Not Found" error for the line >> app_data = data_bag_item('spring-petclinic', 'app_details') in enabe_webapp recipe. I cound not solve it even I have tried many things. Do you have any idea for the reason of this problem ? Below is the error log.

Thanks

Recipe Compile Error in /var/chef/cache/cookbooks/spring-petclinic-new-app-deploy/recipes/default.rb
================================================================================

Net::HTTPServerException
------------------------
404 "Object Not Found"

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/spring-petclinic-new-app-deploy/recipes/enable_webapp.rb:12:in `from_file'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in

  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in
lude_recipe'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in

  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in
pe'
  /var/chef/cache/cookbooks/spring-petclinic-new-app-deploy/recipes/default.rb:20:in `from_file'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/spring-petclinic-new-app-deploy/recipes/enable_webapp.rb:

  5:  # Copyright (c) 2016 The Authors, All Rights Reserved.
  6:
  7:  # Prepare webapps directory
  8:  include_recipe 'spring-petclinic-new-app-deploy::cleanup_webapp'
  9:
 10:  # Download war to tomcat webapps
 11:  #app_data = data_bag_item('spring-petclinic', 'app_details', IO.read('C:\\Users\\Administrator\\cook
petclinic\\cookbooks\\spring-petclinic-new-app-deploy\\test\\kitchen\\data_bags'))
 12>> app_data = data_bag_item('spring-petclinic', 'app_details')
 13:  #data_bags_path: "test/kitchen/data_bags"
 14:  #app_data = data_bag_item('spring-petclinic', 'app_details' )
 15:  remote_file "#{node['tomcat']['base_dir']}/webapps/#{node['tomcat']['base_instance']}.war.zip" do
 16:    owner 'root'
 17:    group 'root'
 18:    mode '0775'
 19:    source app_data['artifact_location']
 20:    notifies :run, "execute[rename_#{node['tomcat']['base_instance']}.war.zip]", :immediately
 21:  end

Platform:
---------
x86_64-linux

**Comment by atul86244** [comment]
Hi @bilgeadam61 , you need to setup a data bag on your chef server called "spring-petclinic" with a data bag item "app_details". 

Please check this for more details:
https://github.com/atul86244/spring-petclinic/blob/master/cookbooks/spring-petclinic-new-app-deploy/test/kitchen/data_bags/spring-petclinic/app_details.json

**Comment by bilgeadam61** [comment]
Hi Atul

I have setup the data bag and it worked

Thanks
Savas
